#!/bin/sh

export XKB_DEFAULT_OPTIONS=caps:swapescape

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

riverctl map normal Super Return spawn foot
riverctl map normal Super+Shift Return spawn foot

riverctl map normal Super Space spawn "bemenu-run -l 20 --fn 'Hack Nerd Font Mono 16' --margin 400"
# riverctl map normal Super+Shift Space spawn bemenu-run

riverctl map normal Super Q close
riverctl map normal Super+Shift Q exit

# bump the focused to the top of layout stack
# riverctl map normal Super G zoom

riverctl map normal Super B spawn "foot -e bluetuith"

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# music time
riverctl map normal Super M spawn "foot -e ncspot"

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super F toggle-fullscreen
riverctl map normal Super+Shift F toggle-float

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn 'amixer set Master 2%+'
    riverctl map -repeat $mode None XF86AudioLowerVolume  spawn 'amixer set Master 2%-'
    riverctl map $mode None XF86AudioMute         spawn 'amixer set Master toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    ## Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map -repeat $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map -repeat $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
    # riverctl map -repeat $mode None F7 spawn 'brightnessctl set 5%-'
    # riverctl map -repeat $mode None F8 spawn 'brightnessctl set +5%'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
# riverctl rule-add -app-id 'float*' -title 'foo' float


if [ $(hostname) = "hazed" ]; then
    # on the brickbook i dont want to have the screen on as it is always closed
    # the sleep is so that the WM is fully set up when the thing runs
    # (sleep 1 && wlr-randr --output eDP-1 --off) &
    # this needs to be before the bar is set up
    wlr-randr --output eDP-1 --off
else
    riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad disable-while-typing disabled
    riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad tap enabled
    riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad tap-button-map left-right-middle
fi

# riverctl map-switch normal lid close spwan "systemctl suspend"
# riverctl map-switch normal lid close spwan "/home/focus/dev/scripts/lock"
# riverctl map-switch normal lid close spawn "wlr-randr --output eDP-1 --off"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

## statusbar
riverctl spawn "$HOME/.config/river/status"
riverctl spawn "$HOME/.config/river/bar"

# exec-once = wlsunset -t 4500 -S 9:00 -s 19:30
# exec-once = wlsunset -l -23 -L -46
# exec-once = ~/.config/eww/scripts/init
# exec-once = hyprctl setcursor Qogir 24
# exec-once = music init

## Clipboard setup
# exec-once = wl-paste --type text --watch cliphist store
# exec-once = wl-clipboard-history -t

## Screen Shareing
# riverctl spawn pipewire
# riverctl spawn wireplumber

## Correctness setup
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# # exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# # exec-once = systemctl --user restart pipewire
# # exec-once = /usr/lib/polkit-kde-authentication-agent-1

## notification
riverctl spawn mako

## Input
riverctl spawn fcitx5
# riverctl spawn nm-applet

## wallpaper
riverctl spawn swww-daemon
# exec-once = cycle-wallpaper

# switch-0-5-Lid_Switch
# keyboard-0-1-Power_Button

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal
