#!/bin/sh

export PS1="$(tput setaf 1)\u$(tput setaf 2)@$(tput setaf 4)\H $(tput setaf 5)\w $(tput sgr0)\n\$ "

export PATH="$HOME/.local/bin:$HOME/.local/share/node/bin:$PATH"
export EDITOR="nv"

# alias search='find . | fzf | xargs'
# alias searchf='find . -type f | fzf | xargs'
# alias searchdir='find . -type d | fzf | xargs'
# alias lr='br -sdp'

alias ..='cd ..'
# alias h='history'
# alias c='clear'
alias o='xdg-open'
# alias m='mpv'
# alias i='imv'
alias e="$EDITOR"
alias z='zathura'
alias n='newsboat'

alias cp='cp -ivr'
alias mv='mv -iv'
alias rm='rm -vI' # -I is not posix

alias mkd='mkdir -pv'
alias bat='bat --plain'

alias yt='yt-dlp --embed-metadata -i'
alias yta='yt-dlp --embed-metadata -i -x -f bestaudio/best --audio-format vorbis'
alias ytt='yt-dlp --embed-metadata -i --skip-download --write-thumbnail'

alias wget='wget --hsts-file /dev/null'
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'
alias vdiff='nvim -d'
alias sdn='shutdown -h now'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias nmutt='neomutt'
alias ttc='tty-clock -c -C 7 -r -f "%A, %B %d"'
alias lynx='lynx -vikeys'

# alias doom1='chocolate-doom -iwad $HOME/dox/games/DOOM1.wad'
# alias doom2='chocolate-doom -iwad $HOME/dox/games/DOOM2.wad'

# cd and ls after
cd() {
    builtin cd "$@"
    ls --color=always
}

if command -v fzf-share >/dev/null; then
    source "$(fzf-share)/key-bindings.bash"
    # source "$(fzf-share)/completion.bash"
fi

function br {
    local cmd cmd_file code
    cmd_file=$(mktemp)
    if broot --outcmd "$cmd_file" "$@"; then
        cmd=$(<"$cmd_file")
        command rm -f "$cmd_file"
        eval "$cmd"
    else
        code=$?
        command rm -f "$cmd_file"
        return "$code"
    fi
}
